# 실습 1
> 0부터 5사이 랜덤한 값이 담긴 3x5 array를 만들어 봅시다!


In [2]:
import numpy as np
array = np.random.randint(0,5,(3,5))

array

array([[3, 4, 0, 3, 2],
       [0, 2, 3, 3, 1],
       [1, 0, 1, 2, 0]])

# 실습 2, 3

In [ ]:
import numpy as np

print("1차원 array")
array = np.arange(10)
print(array)

# Q1. array의 자료형을 출력해 보세요.
print(type(array))

# Q2. array의 차원을 출력해 보세요.
print(array.ndim)

# Q3. array의 모양을 출력해 보세요.
print(array.shape)

# Q4. array의 크기를 출력해 보세요.
print(array.size)

# Q5. array의 dtype(data type)을 출력해 보세요.
print(array.dtype)

# Q6. array의 인덱스 5의 요소를 출력해 보세요.
print(array[5])

# Q7. array의 인덱스 3의 요소부터 인덱스 5 요소까지 출력해 보세요.
print(array[3:6])


In [ ]:
import numpy as np

print("2차원 array")
matrix = np.arange(1, 16).reshape(3,5)  #1부터 15까지 들어있는 (3,5)짜리 배열을 만듭니다.
print(matrix)


# Q1. matrix의 자료형을 출력해 보세요.
print(type(matrix))

# Q2. matrix의 차원을 출력해 보세요.
print(matrix.ndim)

# Q3. matrix의 모양을 출력해 보세요.
print(matrix.shape)

# Q4. matrix의 크기를 출력해 보세요.
print(matrix.size)

# Q5. matrix의 dtype(data type)을 출력해 보세요.
print(matrix.dtype)

# Q6. matrix의 (2,3) 인덱스의 요소를 출력해 보세요.
print(matrix[2,3])

# Q7. matrix의 행은 인덱스 0부터 인덱스 1까지, 열은 인덱스 1부터 인덱스 3까지 출력해 보세요.
print(matrix[0:2,1:4])


# 실습 4, 5, 6

Reshape & 이어붙이고 나누기 (1)

In [1]:
import numpy as np

print("array")
array = np.arange(8)
print(array)
print("shape : ", array.shape, "\n")

# Q1. array를 (2,4) 크기로 reshape하여 matrix에 저장한 뒤 matrix와 그의 shape를 출력해 보세요.
print("# reshape (2, 4)")
matrix = array.reshape(2,4)


print(matrix)
print("shape : ", matrix.shape)


array
[0 1 2 3 4 5 6 7]
shape :  (8,) 

# reshape (2, 4)
[[0 1 2 3]
 [4 5 6 7]]
shape :  (2, 4)


Reshape & 이어붙이고 나누기 (2)

In [4]:
import numpy as np

print("matrix")
matrix = np.array([[0,1,2,3],
                   [4,5,6,7]])
print(matrix)
print("shape : ", matrix.shape, "\n")


# Q1. matrix 두 개를 세로로 붙이기 
m = np.concatenate([matrix, matrix], axis =0 )
print(m)


# Q2. matrix 두 개를 가로로 붙이기

n = np.concatenate([matrix, matrix], axis = 1)
print(n)



matrix
[[0 1 2 3]
 [4 5 6 7]]
shape :  (2, 4) 

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]


Reshape & 이어붙이고 나누기 (3)

In [5]:
import numpy as np

print("matrix")
matrix = np.array([[ 0, 1, 2, 3],
                   [ 4, 5, 6, 7],
                   [ 8, 9,10,11], 
                   [12,13,14,15]])
print(matrix, "\n")

# Q1. matrix를 [3] 행에서 axis 0으로 나누기
'''
[[0  1   2  3]
 [4  5   6  7]
 [8  9  10 11]],

 [12 13 14 15]
'''
a, b = np.split(matrix, [3] , axis =0 )

print(a, "\n")
print(b, "\n")


# Q2. matrix를 [1] 열에서 axis 1로 나누기

'''
[[ 0]
 [ 4]
 [ 8]
 [12]],

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
'''

c, d = np.split(matrix, [1] , axis =1 )

print(c, "\n")
print(d)


matrix
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]] 

[[ 0]
 [ 4]
 [ 8]
 [12]] 

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


# 실습 7

In [6]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array)


# Q1. array에 5를 더한 값을 출력해 보세요.
print(array+5)
# Q2. array에 5를 뺀 값을 출력해 보세요.
print(array-5)
# Q3. array에 5를 곱한 값을 출력해 보세요.
print(array*5)

# Q4. array를 5로 나눈 값을 출력해 보세요.
print(array/5)


# Q5. array에 array2를 더한 값을 출력해 보세요.    
array2 = np.array([5,4,3,2,1])

print(array+array2)


# Q6. array에 array2를 뺀 값을 출력해 보세요.
print(array-array2)


[1 2 3 4 5]
[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[6 6 6 6 6]
[-4 -2  0  2  4]


# 실습 8

In [7]:
import numpy as np

'''
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] 배열 A와

 [0 1 2 3 4 5] 배열 B를 선언하고, 덧셈 연산해 보세요.
'''

A = np.arange(6).reshape(6,1)
B = np.arange(6)

print(A+B)

[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]


# 실습 9, 10

In [8]:
import numpy as np

matrix = np.arange(8).reshape((2, 4))
print(matrix)

# Q1. sum 함수로 matrix의 총 합계를 구해 출력해 보세요.
print(np.sum(matrix))

# Q2. max 함수로 matrix 중 최댓값을 구해 출력해 보세요.
print(np.max(matrix))

# Q3. min 함수로 matrix 중 최솟값을 구해 출력해 보세요.
print(np.min(matrix))

# Q4. mean 함수로 matrix의 평균값을 구해 출력해 보세요.
print(np.mean(matrix))

# Q5. sum 함수의 axis 매개변수로 각 열의 합을 구해 출력해 보세요.
print(np.sum(matrix,axis = 0))

# Q6. sum 함수의 axis 매개변수로 각 행의 합을 구해 출력해 보세요.
print(np.sum(matrix, axis = 1))

# Q7. std 함수로 matrix의 표준편차를 구해 출력해 보세요.
print(np.std(matrix))

# Q8. 마스킹 연산을 이용하여 matrix 중 5보다 작은 수들만 추출하여 출력해 보세요.
print(matrix[matrix <5 ])

[[0 1 2 3]
 [4 5 6 7]]
28
7
0
3.5
[ 4  6  8 10]
[ 6 22]
2.29128784747792
[0 1 2 3 4]


양치기 소년
주어진 daily_liar_data 배열은 양치기 소년이 100일 동안 한 말을 정리한 배열입니다.

0은 거짓말을 한 날이고, 1은 거짓말을 하지 않은 날입니다.

양치기 소년이 100일 중 거짓말을 총 몇 번 했는지, 그 횟수를 세어 정확히 출력해 주세요.



In [13]:

import numpy as np

daily_liar_data = [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]


# 양치기 소년이 거짓말을 몇 번 했는지 구하여 출력해 주세요.


print(len(daily_liar_data)-sum(daily_liar_data))


71